custom_data:
  umcu_checkqc:
    id: "umcu_checkqc"
    section_name: "UMCU CheckQC"
    plot_type: "table"
sp:
  umcu_checkqc:
    fn: "*checkqc_summary.csv"
table_cond_formatting_rules:
  umcu_checkqc:
    pass:
      - s_eq: "PASS"
    fail:
      - s_eq: "FAIL"
